version: '3.8'

services:
  # Neo4j
  neo4j:
    image: neo4j:5.26.0
    container_name: fraud-neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/fraudpassword
      - NEO4J_server_memory_heap_max__size=4G
      - NEO4J_server_memory_pagecache_size=2G
    volumes:
      - neo4j_data:/data
    networks:
      - fraud-network

  # API FastAPI
  fraud-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fraud-api
    ports:
      - "8000:8000"
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=fraudpassword
    volumes:
      - ./models:/app/models
    depends_on:
      - neo4j
    networks:
      - fraud-network

  # Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: fraud-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - fraud-network
    depends_on:
      - fraud-api

  # Grafana
  grafana:
    image: grafana/grafana:latest
    container_name: fraud-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    networks:
      - fraud-network
    depends_on:
      - prometheus

volumes:
  neo4j_data:
  grafana_data:

networks:
  fraud-network:
    driver: bridge